/*
 * @description: 抽离开源版本
 * @Author: chuyinlong
 * @Date: 2021-08-20 17:29:10
 * @LastEditors: chuyinlong
 * @LastEditTime: 2021-08-25 09:38:21
 */
const template = [
  {
    borderWidth: 0,
    img:
      "https://img.yzcdn.cn/public_files/2017/11/03/60342dcc32a039ef613a14db0291f3ab.png",
    title: "1行2个",
    layoutWidth: 2,
    layoutHeight: 1,
    showMethod: 0,
    pageMargin: 0,
    width: 2,
    subEntry: [
      {
        x: 0,
        y: 0,
        width: 1,
        height: 1,
        img: "",
        link: {
          id: "",
          type: 0,
          name: "",
          url: "",
          append: "",
        },
        linkName: "",
      },
      {
        x: 1,
        y: 0,
        width: 1,
        height: 1,
        img: "",
        link: {
          id: "",
          type: 0,
          name: "",
          url: "",
          append: "",
        },
        linkName: "",
      },
    ],
  },
  {
    borderWidth: 0,
    img:
      "https://img.yzcdn.cn/public_files/2017/11/03/6268ad7610bdc42ece83ac20379b28e9.png",
    title: "1行3个",
    layoutWidth: 3,
    layoutHeight: 1,
    showMethod: 1,
    pageMargin: 0,
    width: 3,
    subEntry: [
      {
        x: 0,
        y: 0,
        width: 1,
        height: 1,
        img: "",
        link: {
          id: "",
          type: 0,
          name: "",
          url: "",
          append: "",
        },
        linkName: "",
      },
      {
        x: 1,
        y: 0,
        width: 1,
        height: 1,
        img: "",
        link: {
          id: "",
          type: 0,
          name: "",
          url: "",
          append: "",
        },
        linkName: "",
      },
      {
        x: 2,
        y: 0,
        width: 1,
        height: 1,
        img: "",
        link: {
          id: "",
          type: 0,
          name: "",
          url: "",
          append: "",
        },
        linkName: "",
      },
    ],
  },
  {
    borderWidth: 0,
    img:
      "https://img.yzcdn.cn/public_files/2017/11/03/2781e737570549d45604867d8045aada.png",
    title: "1行4个",
    layoutWidth: 4,
    layoutHeight: 1,
    showMethod: 2,
    pageMargin: 0,
    width: 4,
    subEntry: [
      {
        x: 0,
        y: 0,
        width: 1,
        height: 1,
        img: "",
        link: {
          id: "",
          type: 0,
          name: "",
          url: "",
          append: "",
        },
        linkName: "",
      },
      {
        x: 1,
        y: 0,
        width: 1,
        height: 1,
        img: "",
        link: {
          id: "",
          type: 0,
          name: "",
          url: "",
          append: "",
        },
        linkName: "",
      },
      {
        x: 2,
        y: 0,
        width: 1,
        height: 1,
        img: "",
        link: {
          id: "",
          type: 0,
          name: "",
          url: "",
          append: "",
        },
        linkName: "",
      },
      {
        x: 3,
        y: 0,
        width: 1,
        height: 1,
        img: "",
        link: {
          id: "",
          type: 0,
          name: "",
          url: "",
          append: "",
        },
        linkName: "",
      },
    ],
  },
  {
    borderWidth: 0,
    img:
      "https://img.yzcdn.cn/public_files/2017/11/09/83a31af68ff039a2a636151fa7fa9279.png",
    title: "2左2右",
    layoutWidth: 4,
    layoutHeight: 4,
    showMethod: 3,
    pageMargin: 0,
    width: 4,
    subEntry: [
      {
        x: 0,
        y: 0,
        width: 2,
        height: 2,
        img: "",
        link: {
          id: "",
          type: 0,
          name: "",
          url: "",
          append: "",
        },
        linkName: "",
      },
      {
        x: 2,
        y: 0,
        width: 2,
        height: 2,
        img: "",
        link: {
          id: "",
          type: 0,
          name: "",
          url: "",
          append: "",
        },
        linkName: "",
      },
      {
        x: 0,
        y: 2,
        width: 2,
        height: 2,
        img: "",
        link: {
          id: "",
          type: 0,
          name: "",
          url: "",
          append: "",
        },
        linkName: "",
      },
      {
        x: 2,
        y: 2,
        width: 2,
        height: 2,
        img: "",
        link: {
          id: "",
          type: 0,
          name: "",
          url: "",
          append: "",
        },
        linkName: "",
      },
    ],
  },
  {
    borderWidth: 0,
    img:
      "https://img.yzcdn.cn/public_files/2017/11/09/ba54374788fe99d976963da2fa7eca6e.png",
    title: "1左2右",
    layoutWidth: 4,
    layoutHeight: 4,
    showMethod: 3,
    pageMargin: 0,
    width: 4,
    subEntry: [
      {
        x: 0,
        y: 0,
        width: 2,
        height: 4,
        img: "",
        link: {
          id: "",
          type: 0,
          name: "",
          url: "",
          append: "",
        },
        linkName: "",
      },
      {
        x: 2,
        y: 0,
        width: 2,
        height: 2,
        img: "",
        link: {
          id: "",
          type: 0,
          name: "",
          url: "",
          append: "",
        },
        linkName: "",
      },
      {
        x: 2,
        y: 2,
        width: 2,
        height: 2,
        img: "",
        link: {
          id: "",
          type: 0,
          name: "",
          url: "",
          append: "",
        },
        linkName: "",
      },
    ],
  },
  {
    borderWidth: 0,
    img:
      "https://img.yzcdn.cn/public_files/2017/11/09/7b4cdf2cc81d386c2ec316cde4d7c419.png",
    title: "1上2下",
    layoutWidth: 4,
    layoutHeight: 4,
    showMethod: 4,
    pageMargin: 0,
    width: 4,
    subEntry: [
      {
        x: 0,
        y: 0,
        width: 4,
        height: 2,
        img: "",
        link: {
          id: "",
          type: 0,
          name: "",
          url: "",
          append: "",
        },
        linkName: "",
      },
      {
        x: 0,
        y: 2,
        width: 2,
        height: 2,
        img: "",
        link: {
          id: "",
          type: 0,
          name: "",
          url: "",
          append: "",
        },
        linkName: "",
      },
      {
        x: 2,
        y: 2,
        width: 2,
        height: 2,
        img: "",
        link: {
          id: "",
          type: 0,
          name: "",
          url: "",
          append: "",
        },
        linkName: "",
      },
    ],
  },
  {
    borderWidth: 0,
    img:
      "https://img.yzcdn.cn/public_files/2017/11/09/baf20bd9462316851c81e47f8ae2cadf.png",
    title: "1左3右",
    layoutWidth: 4,
    layoutHeight: 4,
    showMethod: 5,
    pageMargin: 0,
    width: 4,
    subEntry: [
      {
        x: 0,
        y: 0,
        width: 2,
        height: 4,
        img: "",
        link: {
          id: "",
          type: 0,
          name: "",
          url: "",
          append: "",
        },
        linkName: "",
      },
      {
        x: 2,
        y: 0,
        width: 2,
        height: 2,
        img: "",
        link: {
          id: "",
          type: 0,
          name: "",
          url: "",
          append: "",
        },
        linkName: "",
      },
      {
        x: 2,
        y: 2,
        width: 1,
        height: 2,
        img: "",
        link: {
          id: "",
          type: 0,
          name: "",
          url: "",
          append: "",
        },
        linkName: "",
      },
      {
        x: 3,
        y: 2,
        width: 1,
        height: 2,
        img: "",
        link: {
          id: "",
          type: 0,
          name: "",
          url: "",
          append: "",
        },
        linkName: "",
      },
    ],
  },
  {
    borderWidth: 0,
    img:
      "https://img.yzcdn.cn/public_files/2017/11/03/266e578c7470586e6be573cb0fc4d699.png",
    title: "自定义",
    layoutWidth: 0,
    layoutHeight: 0,
    showMethod: 0,
    pageMargin: 0,
    width: 4,
    subEntry: [],
  },
];

export default template;
